const String QUIZ_INFO =
    "Our *Lifestyle & Work Assessment Tool* provides you with an exploration "
    "of 8 carefully selected perspectives of effectiveness. Mastering these "
    "perspectives will collectively increase your production capacity to new "
    "unchartered levels of results when it comes to work-life balance. They "
    "lead to having less experience of stress and more experience of "
    "well-being, focus and peace of mind.\n\nFor each perspective you are "
    "exploring, you have two different levels to reflect on.\n*Level 1:* "
    "Reflect on 4 different statements of the current perspective. Choose the "
    "statement that is the best match of your current experience.\n*Level 2:* "
    "Here is where you go deeper and consider whether the statement you chose "
    "is worse, better or exactly as described. At this point your chosen "
    "answer will be evaluated in comparison to what is possible in this area. "
    "\nThen, simply click the Next-button, to move to the next perspective."
    "\n\n*At the end of our Lifestyle & Work Assessment Tool you will be "
    "provided with a total score.* Very stimulating reading and an interesting "
    "exercise to do on a regular basis to note your progress!\n\nAre you ready "
    "to take this on? Why not, take the opportunity, and do it right now!\n*"
    "If you are thinking, you’ll come back and do it later, you know what will "
    "happen. You will honestly, probably never come back.* Don’t miss this "
    "opportunity to stop and see what is really going on in your life – an "
    "opportunity that has been *a life saver for so many people before you!*"
    "\n\nWe are here for you,\nThe HAST Team\n";

const String INFO_TEXT =
    "*HAST Utveckling offer services of consulting, training, "
    "seminars and coaching as experts in the areas of Leadership, Communication, "
    "Effectiveness and Team Development.* The company was founded in 2001 and have since then "
    "created results for managers, leaders and their personnel in over 40% of Sweden’s 100 largest companies. "
    "They have travelled to do work in more than 15 countries and have had participants in our programs "
    "from more than 40 different nations worldwide. \n\n*We at HAST Utveckling, provide the climate needed for "
    "individuals and groups to take a good look at and discover key principles, behaviors and unaware preconceptions* "
    "that keep us as human beings from reaching our true potential. These discoveries lead to waking people up to what "
    "is really going on. From real insight you hardly need to tell people what to do. Instead, people have a natural tendency "
    "to automatically implement behavior changes creating a new level of sustainable results. Fascinating! \n\n*These changes result in "
    "increased peace of mind, focus and productivity* as well as better worklife balance and new possibilities of innovation."
    " We turn stress to calm, conflict to teamwork, limitations to new results and managers to true leaders. \n\n*We asked some of "
    "our most cherished customers,* such as The West Sweden Chamber of Commerce, Volvo Penta, ABB, RISE (Research Institutes of Sweden),"
    " Preem, The Swedish Transport Administration and others, to describe, in their own words, what comes to mind when they think of HAST."
    " Here are a few examples of their comments: \n\n    /“Great structures. Keep their promises. Clear processes and \n    competent people.”/"
    "\n\n    /“Your level of competence is high, like many others, but you\n    serve them with warmth and humor in a way that makes\n    you stand out "
    "from the crowd.”/ \n\n    /“HAST dares to “touch on” matters that are not always\n    comfortable to take a look at and that other suppliers just\n    let go of.”/";

const String HAST_WELCOME = "*Welcome!*\n\n"
    "We at HAST Utveckling are pleased to offer our much-appreciated *Lifestyle & Work Assessment Tool.* When completed, it will point you towards the actual state of your work-life balance at this moment in time.\n\n"
    "Take this opportunity, to pause in the midst of everyday worklife and perform this self-assessment which *focuses on 8 carefully selected perspectives of effectiveness.* Mastering these perspectives will collectively increase your production capacity to new unchartered levels of results.\n\n"
    "*This tool will provide you with clarification* on what areas you have already successfully mastered and in what areas you could greatly benefit from new insights and tools.\n\n"
    "We provide this tool for anyone who is curious as to where you are at today, compared to what is possible! *We at HAST, love honest conversations and transparency*, so… as you view your personal total score at the end of this self-assessment, you may decide to connect with us and have a coaching conversation with us to explore your missing pieces – or not. The choice is yours!\n\n"
    "At your service,\n"
    "The HAST Team";
