name: hast_app
description: An application developed for HAST

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
version: 1.0.0+1

# Cranked up the number to guarantee null safety
environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter_web_plugins:
    sdk: flutter
  flutter:
    sdk: flutter
  provider: '>=5.0.0-nullsafety.5 <6.0.0'
  json_annotation: '>=4.0.0'
  url_launcher: ^6.0.3
  simple_rich_text: ^2.0.46
  google_fonts: ^2.1.0
  flutter_svg: ^0.22.0
  shared_preferences: ^2.0.5
  shared_preferences_web: ^2.0.0

  #cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: '>=2.0.0'
  json_serializable: '>=4.1.0'


# The following section is specific to Flutter.
flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/quizzes/
