name: hast_app
description: An application developed for HAST

publish_to: 'none' # Remove this line if you wish to publish to pub.dev



  # \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
  # ////////////////////////////////////////////////////////////////////////////////////////////
  # TODO Want to add more quizzes? - look at the bottom of this document!
  # \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
  # ////////////////////////////////////////////////////////////////////////////////////////////



# The following defines the version and build number for your application.
version: 1.0.0+1

# Cranked up the number to guarantee null safety
environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter_web_plugins:
    sdk: flutter
  flutter:
    sdk: flutter
  provider: '>=5.0.0-nullsafety.5 <6.0.0'
  json_annotation: '>=4.0.0'


  #cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: '>=2.0.0'
  json_serializable: '>=4.1.0'


# The following section is specific to Flutter.
flutter:

  uses-material-design: true

  assets:
    - assets/images/hastlogga.png
    - assets/images/4.png



    # ////////////////////////////////////////////////////////////////////////////////////////////
    # IGNORE EVERYTHING ABOVE HERE
    # \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\



    # FOR HAST
    # TO ADD MORE QUIZZES, ADD JSON FILE NAMES HERE
    # FOR EXAMPLE: " - assets/quizzes/[Name of file].json "
    - assets/quizzes/ReflectionQuiz.json
    - assets/quizzes/example.json